import type { ResumeCompany } from './types'

/**
 * Employment / company history (newest first).
 * Localized role, summary and impact bullets live in i18n under `resume.companies.<i18nKey>`.
 */
export const resumeCompanies: ResumeCompany[] = [
  {
    id: 'bigmike-solutions',
    i18nKey: 'bigmikeSolutions',
    name: 'BigMikeSolutions',
    url: 'https://bigmikesolutions.pl',
    start: '2014-05',
    countInTechSummary: false,
    tech: [
      'Go',
      'Java',
      'Kotlin',
      'TypeScript',
      'React',
      'PostgreSQL',
      'AWS',
      'GCP',
      'Azure',
      'Kubernetes',
      'Terraform',
      'GraphQL',
      'gRPC',
      'REST',
      'Docker',
      'GitLab CI',
      'GitHub Actions',
    ],
  },
  {
    id: 'shell-recharge',
    i18nKey: 'shellRecharge',
    name: 'Shell Recharge',
    url: 'https://www.shell.com/shellrecharge',
    start: '2021-05',
    end: '2025-05',
    tech: [
      'Go',
      'PostgreSQL',
      'Kafka',
      'Flink',
      'GraphQL',
      'Apollo Federation',
      'gRPC',
      'REST',
      'Docker',
      'Kubernetes',
      'AWS',
      'Terraform',
      'GitLab CI',
      'Vault',
      'Python',
      'Node.js',
    ],
  },
  {
    id: 'herolynx',
    i18nKey: 'herolynx',
    name: 'HeroLynx',
    url: 'https://herolynx.com',
    start: '2015-01',
    end: '2021-11',
    tech: [
      'Go',
      'Kotlin',
      'Android',
      'React',
      'Firebase',
      'PostgreSQL',
      'FaunaDB',
      'GCP',
      'Kubernetes',
      'Terraform',
      'GraphQL',
    ],
  },
  {
    id: 'form3',
    i18nKey: 'form3',
    name: 'Form3',
    url: 'https://www.form3.tech',
    start: '2018-12',
    end: '2021-04',
    tech: [
      'Java',
      'Spring',
      'Go',
      'PostgreSQL',
      'Docker',
      'Kubernetes',
      'Consul',
      'Vault',
      'NATS',
      'Kong',
      'Linkerd',
      'AWS',
      'Terraform',
      'GitHub Actions',
      'Prometheus',
      'Grafana',
      'ELK',
      'PACT',
    ],
  },
  {
    id: 'huuuge-games',
    i18nKey: 'huuugeGames',
    name: 'Huuuge Games',
    url: 'https://huuugegames.com',
    start: '2017-11',
    end: '2018-11',
    tech: [
      'Scala',
      'Akka',
      'Go',
      'Docker',
      'Kubernetes',
      'ScyllaDB',
      'PostgreSQL',
      'NATS',
      'Jenkins',
      'Terraform',
      'AWS',
    ],
  },
  {
    id: 'siili',
    i18nKey: 'siili',
    name: 'Siili Solutions Poland',
    url: 'https://www.siili.com',
    start: '2014-04',
    end: '2017-06',
    tech: [
      'Java',
      'Spring',
      'Scala',
      'Akka',
      'Kotlin',
      'Go',
      'Docker',
      'Kubernetes',
      'PostgreSQL',
      'NATS',
      'Kafka',
      'Android',
      'Terraform',
      'GitLab CI',
      'Ansible',
      'AWS',
      'Azure',
    ],
  },
  {
    id: 'credit-suisse',
    i18nKey: 'creditSuisse',
    name: 'Credit Suisse',
    url: 'https://www.credit-suisse.com',
    start: '2013-11',
    end: '2014-04',
    tech: ['Java', 'Spring', 'Oracle'],
  },
  {
    id: 'rec-global',
    i18nKey: 'recGlobal',
    name: 'REC Global',
    start: '2011-12',
    end: '2013-10',
    tech: ['Java', 'Spring', 'Scala', 'PostgreSQL', 'Ansible', 'AWS', 'Bash'],
  },
  {
    id: 'capgemini',
    i18nKey: 'capgemini',
    name: 'Capgemini',
    url: 'https://www.capgemini.com',
    start: '2010-09',
    end: '2011-11',
    tech: [
      'Java',
      'Spring',
      'Hibernate',
      'JavaScript',
      'Oracle',
      'PL/SQL',
      'Maven',
      'Weblogic',
    ],
  },
  {
    id: 'nokia',
    i18nKey: 'nokia',
    name: 'Nokia Solutions and Networks',
    url: 'https://www.nokia.com',
    start: '2007-10',
    end: '2010-08',
    tech: [
      'Java',
      'Spring',
      'C++',
      'Oracle',
      'PL/SQL',
      'Python',
      'Perl',
      'Bash',
      'ANTLR',
      'XML',
      'XSLT',
    ],
  },
]
