export const youtubeNewsItems = [
  {
    id: 'abraham-wald',
    type: 'youtube' as const,
    publishedAt: '2026-06-01',
    titleKey: 'youtube.abrahamWald',
    url: 'https://www.youtube.com/watch?v=7_CbSKbLJ7o',
    youtubeId: '7_CbSKbLJ7o',
  },
  {
    id: 'apple-m-processors',
    type: 'youtube' as const,
    publishedAt: '2026-03-12',
    titleKey: 'youtube.appleM',
    url: 'https://www.youtube.com/watch?v=unz9yZUFAYU',
    youtubeId: 'unz9yZUFAYU',
  },
  {
    id: 'ai-understands-text',
    type: 'youtube' as const,
    publishedAt: '2026-01-14',
    titleKey: 'youtube.aiText',
    url: 'https://www.youtube.com/watch?v=Ea5GGLnf-O8',
    youtubeId: 'Ea5GGLnf-O8',
  },
  {
    id: 'ai-revolution-jobs',
    type: 'youtube' as const,
    publishedAt: '2025-12-18',
    titleKey: 'youtube.aiRevolution',
    url: 'https://www.youtube.com/watch?v=SOOdUbEYkKw',
    youtubeId: 'SOOdUbEYkKw',
  },
  {
    id: 'apple-mie',
    type: 'youtube' as const,
    publishedAt: '2025-11-26',
    titleKey: 'youtube.appleMie',
    url: 'https://www.youtube.com/watch?v=zyOrLgHEE6I',
    youtubeId: 'zyOrLgHEE6I',
  },
  {
    id: 'jdd-k8s',
    type: 'youtube' as const,
    publishedAt: '2018-01-15',
    titleKey: 'youtube.jddK8s',
    url: 'https://www.youtube.com/watch?v=-ffKVQzri-s',
    youtubeId: '-ffKVQzri-s',
  },
]
